// Portuguese (pt-BR) interface strings, keyed by the English text used in the code. Study material is not here.
export const PT: Record<string, string> = {
  // Body-system names (labels for the 16 content categories)
  'Respiratory': 'Respiratório',
  'Endocrine': 'Endócrino',
  'Reproductive': 'Reprodutor',
  'Nervous': 'Nervoso',
  'Psychiatry': 'Psiquiatria',
  'Hematology & oncology': 'Hematologia e oncologia',
  'Biochemistry & genetics': 'Bioquímica e genética',
  'Biostatistics & epidemiology': 'Bioestatística e epidemiologia',
  'Musculoskeletal & dermatology': 'Musculoesquelético e dermatologia',
  'Behavioral science': 'Ciências comportamentais',
  'General principles': 'Princípios gerais',
  'Immunology': 'Imunologia',
  'Microbiology': 'Microbiologia',
  'Renal': 'Renal',
  'Cardiovascular': 'Cardiovascular',
  'Gastrointestinal': 'Gastrointestinal',
  // Shared
  'Loading…': 'Carregando…',
  'Retry': 'Tentar de novo',
  'Dismiss': 'Fechar',
  'Saved': 'Salvo',
  'Save': 'Salvar',
  'Back': 'Voltar',
  'Done': 'Concluir',
  'Next': 'Próxima',
  'Finish': 'Finalizar',
  'Pause': 'Pausar',
  'Resume': 'Retomar',
  'Search': 'Buscar',
  'Import': 'Importar',
  'Export': 'Exportar',
  'Email': 'E-mail',
  "Offline — showing saved content. Changes can't be saved until you reconnect.": 'Sem conexão: mostrando o conteúdo salvo. As alterações só poderão ser salvas quando você reconectar.',
  // Login
  "This {what} isn't registered. Ask James to add you.": 'Cadastro não encontrado ({what}). Peça ao James para adicionar você.',
  'Google account': 'conta Google',
  'email': 'e-mail',
  'Sign-in failed.': 'Falha ao entrar.',
  'Check your email for the sign-in link.': 'Confira seu e-mail para o link de acesso.',
  'Step 1 study plan, questions and flashcards.': 'Plano de estudo, questões e flashcards do Step 1.',
  'Continue with Google': 'Continuar com Google',
  'Email me a sign-in link': 'Enviar link de acesso por e-mail',
  // Today and settings
  'Target exam date': 'Data da prova',
  '(minutes)': '(minutos)',
  'Monday': 'Segunda-feira', 'Tuesday': 'Terça-feira', 'Wednesday': 'Quarta-feira', 'Thursday': 'Quinta-feira',
  'Friday': 'Sexta-feira', 'Saturday': 'Sábado', 'Sunday': 'Domingo',
  'Could not save:': 'Não foi possível salvar:',
  'Set a target date in Plan settings to see your countdown.': 'Defina a data da prova nas configurações do plano para ver a contagem regressiva.',
  'Your target date passed. Set a new one in Plan settings.': 'A data da prova já passou. Defina uma nova nas configurações do plano.',
  'Exam day is today': 'A prova é hoje',
  '1 day left': 'falta 1 dia',
  '{n} days left': 'faltam {n} dias',
  'Could not load your plan:': 'Não foi possível carregar seu plano:',
  '{a} of {b} done': '{a} de {b} concluídas',
  'Review {n} flashcards': 'Revisar {n} flashcards',
  'Read': 'Ler',
  'a note in {s}': 'uma nota de {s}',
  'Mark read': 'Marcar como lida',
  'Practice {n} more {s} questions': 'Praticar mais {n} questões de {s}',
  'Answer {n} more {s} questions': 'Responder mais {n} questões de {s}',
  'Answer {n} {s} questions': 'Responder {n} questões de {s}',
  'Your plan': 'Seu plano',
  'Maximum is 600 minutes, using 600.': 'O máximo é 600 minutos; usando 600.',
  'Take the diagnostic': 'Faça o diagnóstico',
  'to calibrate your plan.': 'para calibrar seu plano.',
  'Exam countdown': 'Contagem regressiva',
  'Target date:': 'Data da prova:',
  'Today': 'Hoje',
  'Minutes today': 'Minutos hoje',
  'This week': 'Esta semana',
  'Monday to Sunday': 'Segunda a domingo',
  '{a} of {b} min this week': '{a} de {b} min nesta semana',
  'Minutes this week': 'Minutos nesta semana',
  'Your tasks': 'Suas tarefas',
  '{n} min planned': '{n} min planejados',
  'No study time set for today.': 'Nenhum tempo de estudo definido para hoje.',
  'Nothing to do today.': 'Nada para fazer hoje.',
  'done': 'concluída',
  'All done for today.': 'Tudo concluído por hoje.',
  'Plans update with your answers.': 'O plano se atualiza com suas respostas.',
  'Rebuild plan': 'Refazer plano',
  'Where you stand': 'Como você está',
  'Weakest first': 'Mais fracos primeiro',
  'In plan': 'No plano',
  '{n} answered': '{n} respondidas',
  'Not started': 'Não iniciado',
  'Plan settings': 'Configurações do plano',
  // Flashcards
  'Could not save your rating: {m}': 'Não foi possível salvar sua avaliação: {m}',
  'Could not update status: {m}': 'Não foi possível atualizar o status: {m}',
  'What is wrong? (optional)': 'O que está errado? (opcional)',
  'Flagged for review.': 'Marcado para revisão.',
  'Could not load cards:': 'Não foi possível carregar os cartões:',
  'Nothing due. Come back later, or add cards on the Import tab.': 'Nada para revisar agora. Volte mais tarde ou adicione cartões na aba Importar.',
  '{n} left': 'faltam {n}',
  'Show answer': 'Mostrar resposta',
  'Again': 'De novo', 'Hard': 'Difícil', 'Good': 'Bom', 'Easy': 'Fácil',
  'Flag as wrong': 'Marcar como errado',
  'Marked verified.': 'Marcado como verificado.',
  'Mark verified': 'Marcar como verificado',
  // Diagnostic
  'Could not load the diagnostic:': 'Não foi possível carregar o diagnóstico:',
  '{a} of {b} answered': '{a} de {b} respondidas',
  'A diagnostic is already in progress on another device. Reload to resume it.': 'Já há um diagnóstico em andamento em outro dispositivo. Recarregue para retomá-lo.',
  'Could not start the diagnostic: {m}': 'Não foi possível iniciar o diagnóstico: {m}',
  'Could not finish the diagnostic: {m}': 'Não foi possível concluir o diagnóstico: {m}',
  'Could not save your answer: {m}': 'Não foi possível salvar sua resposta: {m}',
  'Abandon this diagnostic? Answers already given stay in your history.': 'Abandonar este diagnóstico? As respostas já dadas continuam no seu histórico.',
  'Could not start over: {m}': 'Não foi possível recomeçar: {m}',
  'This sitting: {n} answered': 'Esta sessão: {n} respondidas',
  'Your answer:': 'Sua resposta:',
  'Correct answer:': 'Resposta correta:',
  'See results': 'Ver resultados',
  '{c} of {t} correct': '{c} de {t} corretas',
  'not answered': 'não respondidas',
  '{c} of {a} correct ({p})': '{c} de {a} corretas ({p})',
  'low confidence': 'baixa confiança',
  'Start another diagnostic': 'Iniciar outro diagnóstico',
  'Start over': 'Recomeçar',
  'Diagnostic': 'Diagnóstico',
  'The diagnostic samples about 100 questions across systems to find where you stand. Answer in short sittings: pause any time and resume later. Explanations appear when you pause or finish.': 'O diagnóstico seleciona cerca de 100 questões de todos os sistemas para mostrar onde você está. Responda em sessões curtas: pause quando quiser e retome depois. As explicações aparecem quando você pausa ou termina.',
  'Start diagnostic': 'Iniciar diagnóstico',
  'No questions yet.': 'Ainda não há questões.',
  // Search
  'card': 'cartão', 'question': 'questão', 'note': 'nota',
  'This item is no longer available.': 'Este item não está mais disponível.',
  'Could not open:': 'Não foi possível abrir:',
  'Search failed: {m}': 'A busca falhou: {m}',
  'Search cards, questions, notes': 'Buscar cartões, questões, notas',
  'No results.': 'Nenhum resultado.',
  // Import / export
  'Import stopped after {a} of {b} saved: {m}': 'Importação interrompida após {a} de {b} salvos: {m}',
  'Export failed: {m}': 'Falha na exportação: {m}',
  'Import failed: {m}': 'Falha na importação: {m}',
  'Cards: Anki "Notes in Plain Text" export or a two-column CSV (front, back).': 'Cartões: exportação "Notes in Plain Text" do Anki ou CSV de duas colunas (frente, verso).',
  'Questions: a JSON array of': 'Questões: uma lista JSON de',
  'Download my backup (JSON)': 'Baixar meu backup (JSON)',
  // Notes
  'Could not load notes:': 'Não foi possível carregar as notas:',
  'No notes yet.': 'Ainda não há notas.',
  // Questions
  'Could not update question: {m}': 'Não foi possível atualizar a questão: {m}',
  '{n} not saved': '{n} não salvas',
  '{n} rejected by the server': '{n} recusadas pelo servidor',
  '. Rejected: {list}.': '. Recusadas: {list}.',
  'Could not save results': 'Não foi possível salvar os resultados',
  'Could not save your answer': 'Não foi possível salvar sua resposta',
  'of {n}': 'de {n}',
  'Could not load questions:': 'Não foi possível carregar as questões:',
  'questions': 'questões',
  'Start practice set ({n} {w} in {s})': 'Iniciar prática ({n} {w} em {s})',
  'Resume planned set ({n} {w} left in {s}, {d} done)': 'Retomar conjunto planejado ({n} {w} restantes em {s}, {d} concluídas)',
  'Start planned set ({n} {w} in {s})': 'Iniciar conjunto planejado ({n} {w} em {s})',
  'Practice questions': 'Questões de prática',
  '{n} questions available.': '{n} questões disponíveis.',
  '(loading history…)': '(carregando histórico…)',
  'Start tutor session ({n} questions)': 'Iniciar sessão tutor ({n} questões)',
  'Start timed session ({n} questions, {m} min)': 'Iniciar sessão cronometrada ({n} questões, {m} min)',
  '{c} of {t} correct ({p}%)': '{c} de {t} corretas ({p}%)',
  'Review {n} missed': 'Revisar {n} erradas',
  'Back to Today': 'Voltar para Hoje',
  '{time} left': '{time} restantes',
};
